"""
CRACLE - Course and learning path models
"""

import uuid
from datetime import datetime
from sqlalchemy import String, DateTime, Text, Float, Integer, JSON, ForeignKey, Enum as SQLEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID
from app.db.database import Base
import enum


class ContentType(str, enum.Enum):
    COURSE = "course"
    MODULE = "module"
    LESSON = "lesson"
    QUIZ = "quiz"
    SIMULATION = "simulation"
    MICRO_CHALLENGE = "micro_challenge"
    VIDEO = "video"
    PROJECT = "project"


class DifficultyLevel(str, enum.Enum):
    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"
    EXPERT = "expert"


class Course(Base):
    __tablename__ = "courses"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=True)
    category: Mapped[str] = mapped_column(String(100), nullable=False)
    difficulty: Mapped[DifficultyLevel] = mapped_column(SQLEnum(DifficultyLevel), default=DifficultyLevel.BEGINNER)
    estimated_hours: Mapped[float] = mapped_column(Float, default=1.0)
    tags: Mapped[dict] = mapped_column(JSON, default=list)
    learning_objectives: Mapped[dict] = mapped_column(JSON, default=list)
    prerequisites: Mapped[dict] = mapped_column(JSON, default=list)
    is_ai_generated: Mapped[bool] = mapped_column(default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    modules: Mapped[list["Module"]] = relationship(back_populates="course", cascade="all, delete-orphan")


class Module(Base):
    __tablename__ = "modules"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    course_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("courses.id"))
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=True)
    order: Mapped[int] = mapped_column(Integer, default=0)
    content_type: Mapped[ContentType] = mapped_column(SQLEnum(ContentType), default=ContentType.LESSON)
    content_data: Mapped[dict] = mapped_column(JSON, default=dict)  # Flexible content storage
    difficulty: Mapped[DifficultyLevel] = mapped_column(SQLEnum(DifficultyLevel), default=DifficultyLevel.BEGINNER)
    estimated_minutes: Mapped[int] = mapped_column(Integer, default=30)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    course: Mapped["Course"] = relationship(back_populates="modules")


class LearningPath(Base):
    """Generated by the Planner Agent - a personalized sequence of learning activities."""
    __tablename__ = "learning_paths"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"))
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    goal: Mapped[str] = mapped_column(Text, nullable=False)
    target_completion_date: Mapped[datetime] = mapped_column(DateTime, nullable=True)
    skill_level: Mapped[DifficultyLevel] = mapped_column(SQLEnum(DifficultyLevel), default=DifficultyLevel.BEGINNER)
    status: Mapped[str] = mapped_column(String(50), default="active")  # active, paused, completed, abandoned
    progress_pct: Mapped[float] = mapped_column(Float, default=0.0)
    milestones: Mapped[dict] = mapped_column(JSON, default=list)  # List of milestone objects
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    user: Mapped["User"] = relationship(back_populates="learning_paths")
    milestones_rel: Mapped[list["Milestone"]] = relationship(back_populates="learning_path", cascade="all, delete-orphan")


class Milestone(Base):
    """Individual milestones within a learning path."""
    __tablename__ = "milestones"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    learning_path_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("learning_paths.id"))
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=True)
    order: Mapped[int] = mapped_column(Integer, default=0)
    content_type: Mapped[ContentType] = mapped_column(SQLEnum(ContentType), default=ContentType.LESSON)
    content_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=True)  # Reference to course/module
    status: Mapped[str] = mapped_column(String(50), default="pending")  # pending, in_progress, completed, skipped
    due_date: Mapped[datetime] = mapped_column(DateTime, nullable=True)
    completed_at: Mapped[datetime] = mapped_column(DateTime, nullable=True)

    learning_path: Mapped["LearningPath"] = relationship(back_populates="milestones_rel")
